version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g @angular/cli@17
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - echo 'Build Error Simulation'
      - ng build -c production
    finally:
      - echo 'Finally succcess build stage 546'
artifacts:
  base-directory: dist/my-angular-project
  files:
    - '**/*'
